name: EssentialItems
version: 3.1-RELEASE
description: 'Essential commands for any server!'
main: com.essentialitems.Main
depend: []

commands:
    ban:
      description: 'Bans the provided player from the server'
      usage: '/ban <Player> <Reason>'
      
    motd:
      description: 'Opens the MOTD Configuration GUI'
      usage: '/motd'
      
    unban:
      description: 'Unbans the provided player.'
      usage: '/unban <Player>'
      
    tempban:
      description: 'Bans the provided player temporarily from the server.'
      usage: '/tempban <Player> <Time in Minutes> <Reason>'
      
    kick:
      description: 'Kicks the provided player from the server.'
      usage: '/kick <Player> <Reason>'
      
    broadcast:
      description: 'Broadcasts an important message to the server.'
      usage: '/broadcast <Message>'
      aliases: [bc]
      
    warn:
      description: 'Warns the provided player.'
      usage: '/warn <Player> <Reason>'
      
    msg:
      description: 'Sends a private message to the player provide.'
      usage: '/msg <Player> <Reason>'
      aliases: [whisper,tell,pm]
      
    mute:
      description: 'Permanently mutes the provided player from chat.'
      usage: '/mute <Player> <Reason>'
      
    unmute:
      description: 'Unmutes the provided player from chat.'
      usage: '/unmute <Player> <Reason>'
      
    vanish:
      description: 'Toggles whether the user is invisible to other players.'
      usage: '/vanish'
      
    lockdown:
      description: 'Toggles whether the server is in a locked-down state, preventing unauthorized users from joining the server.'
      usage: '/lockdown <Reason>'
      aliases: [ld,lock]
    
    gamemode:
      description: 'Changes the gamemode of the provided player. '
      usage: '/gamemode <Mode> [Player]'
      aliases: [gm]
      
    feed:
      description: 'Feeds the privided player to full hunger.'
      usage: '/feed [Player]'
      aliases: [eat]
      
    heal:
      description: 'Heals the provided player to full health.'
      usage: '/heal [Player]'
      
    workbench:
      description: 'Opens a Crafting Table.'
      usage: '/workbench'
      aliases: [wb,craft,crafting,craftingtable,bench]
      
    chatslow:
      description: 'Adds a cooldown between chat messages.'
      usage: '/chatslow <CoolDown in Seconds>'
      aliases: [slowchat, sc]
    
    tempmute: 
      description: 'Temporarily mutes the provided player from chat.'
      usage: '/tempmute <Player> <Time in Minutes> <Reason>' 
      
    invsee:
      description: 'Views inside of a player inventory.'
      usage: '/invsee <Player>'
      
    essentialitems:
      description: 'EssentialItems Info'
      usage: '/<command>'
      
      
      
      
    
    
      